/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxConfigsRouteImport } from './routes/taxConfigs'
import { Route as TaxCalculatorRouteImport } from './routes/taxCalculator'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const TaxConfigsRoute = TaxConfigsRouteImport.update({
  id: '/taxConfigs',
  path: '/taxConfigs',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxCalculatorRoute = TaxCalculatorRouteImport.update({
  id: '/taxCalculator',
  path: '/taxCalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/taxCalculator': typeof TaxCalculatorRoute
  '/taxConfigs': typeof TaxConfigsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/taxCalculator': typeof TaxCalculatorRoute
  '/taxConfigs': typeof TaxConfigsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/taxCalculator': typeof TaxCalculatorRoute
  '/taxConfigs': typeof TaxConfigsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/taxCalculator' | '/taxConfigs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/taxCalculator' | '/taxConfigs'
  id: '__root__' | '/' | '/$' | '/taxCalculator' | '/taxConfigs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  TaxCalculatorRoute: typeof TaxCalculatorRoute
  TaxConfigsRoute: typeof TaxConfigsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taxConfigs': {
      id: '/taxConfigs'
      path: '/taxConfigs'
      fullPath: '/taxConfigs'
      preLoaderRoute: typeof TaxConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxCalculator': {
      id: '/taxCalculator'
      path: '/taxCalculator'
      fullPath: '/taxCalculator'
      preLoaderRoute: typeof TaxCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  TaxCalculatorRoute: TaxCalculatorRoute,
  TaxConfigsRoute: TaxConfigsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
